name: new_focus_
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  objectbox: ^2.0.0
  objectbox_flutter_libs: any
  path_provider: ^2.0.11

  cupertino_icons: ^1.0.2

  curved_navigation_bar: ^1.0.3




dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_svg: ^0.22.0  

  flutter_lints: ^2.0.0

  build_runner: ^2.0.0
  objectbox_generator: any


flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/img/login_balls.png
    - assets/img/login_logo.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Poppins
      fonts:
        - asset: assets\fonts\Poppins-Black.ttf
        - asset: assets\fonts\Poppins-Bold.ttf
        - asset: assets\fonts\Poppins-ExtraBold.ttf
        - asset: assets\fonts\Poppins-Light.ttf
        - asset: assets\fonts\Poppins-Medium.ttf
        - asset: assets\fonts\Poppins-Regular.ttf
        - asset: assets\fonts\Poppins-SemiBold.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
